title: Axel Forsman
email: axel@axelf.se
description: >-
  My personal website.
github_username: axelf4
mastodon:
  - username: axelf
    instance: mastodon.social

theme: minima
plugins:
  - jekyll-feed
